aws4embeddedlinux/meta-aws-demos

raspberry_pi4/aws_iot_greengrass_64/README.md

change paths for 64-bit image location

---

raspberry_pi4/aws_iot_greengrass_64/rpi4_iot_greengrass_idt.conf

N/A
Add wifi, bluetooth, some networking utilities to the configuration.  There is still a strange delay with ntpd that you may need to force with 'ntpd -g -q' inbetween stopping and starting ntpd. 

Add wifi, bluetooth, some networking utilities

---

renesas-rcar-h3/aws_iot_greengrass/README.md

New walkthrough for meta-aws

---

README.md

add index item for renesas

---

nxp-imx8m/aws-iot-greengrass-v2/README.md

meta-aws runbook for the NXP i.MX8MQEVK
Complete runbook for building, installing and running AWS IoT Greengrass v2.0 on the NXP i.MX8MQEVK

Meta-AWS build instructions for i.MX8M

---

nxp-imx8m/aws-iot-greengrass-v2/README.md

Modified runbook to include instructions for i.MX8MPlus

Support for i.MX8MPlus

---

rpi_foundation/rpi4-64/aws-iot-greengrass-v2/README.md

Re-directed tutorial link to v2 docs

---

meta-aws-demos/conf/devices/agl-renesas/config.conf
meta-aws-demos/conf/devices/qemu/README.md
meta-aws-demos/conf/devices/ti-am572x-idk/config.conf

because of this pending issue:
https://github.com/aws4embeddedlinux/meta-aws/issues/4063

remove aws-iot-device-client

---

.gitmodules
meta-aws-demos/conf/devices/agl-nxp-goldbox/config.conf
meta-aws-demos/conf/devices/agl-nxp-goldbox/layers.conf
meta-aws-demos/conf/devices/ec2-biga/README.md
meta-aws-demos/conf/devices/ec2-biga/config.conf
meta-aws-demos/conf/devices/ec2-biga/layers.conf

This is for a Biga demo project.

Add a biga-ec2 instance configuration.

---

meta-aws-demos/recipes-core/images/aws-demo-image/aws-demo-image.bb

aws-demo-image.bb

---

meta-aws-demos/conf/devices/raspberrypi2/config.conf

raspberrypi2: remove patch, did not help

---

README.md

README.md: fix devices

---

meta-aws-demos/conf/devices/phyboard-mira-imx6-15/layers.conf

phyboard-mira-imx6-15/layers.conf: fix duplicate layers

---

.github/dependabot.yml

dependabot.yml: add weekly submodule update

---

meta-aws-demos/recipes-core/images/aws-iot-greengrass-demo-image/aws-iot-greengrass-demo-image.bb
meta-aws-demos/recipes-core/images/aws-iot-greengrass-demo-simple-image/aws-iot-greengrass-demo-simple-image.bb
meta-aws-demos/recipes-core/images/aws-iot-greengrass-lite-container-demo-image/aws-iot-greengrass-lite-container-demo-image.bb
meta-aws-demos/recipes-core/images/aws-iot-greengrass-lite-demo-image/aws-iot-greengrass-lite-demo-image.bb
meta-aws-demos/recipes-core/images/aws-iot-greengrass-lite-demo-simple-image/aws-iot-greengrass-lite-demo-simple-image.bb
meta-aws-demos/recipes-core/images/aws-iot-greengrass-lite-demo-tiny-image/aws-iot-greengrass-lite-demo-tiny-image.bb
meta-aws-demos/recipes-core/images/aws-iot-greengrass-lite-webrtc-demo-image/aws-iot-greengrass-lite-webrtc-demo-image.bb

gg-images: add cgexec, fix venv

---

.gitmodules

.gitmodules: remove unused layers

---

.github/dependabot.yml

dependabot.yml: from weekly to daily

---

.github/workflows/build-gg-lite.yml
.github/workflows/build-gg.yml

build-gg-lite.yml, build-gg.yml: change way of specifying jobs

---

.gitmodules

Add meta-browser as a git submodule

---

meta-aws-demos/recipes-iot/aws-iot-greengrass/greengrass-lite_git.bb

greengrass-lite: bump git version

---

.github/dependabot.yml

2025 10 07 master next bump ggl
